export const dynamic = 'force-dynamic'
import "./globals.css";
import JioCinemaHeader from "@/components/section/Header";
import Footer from "@/components/section/Footer";
import {Inter} from "next/font/google";
const inter = Inter({ subsets: ["latin"]});
import StoreProvider from "@/providers/storeProvider";
import { Toaster } from "@/components/ui/sonner";





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className}antialiased`}
      >
       
        <StoreProvider>
          
         
        
    
        
          
        <JioCinemaHeader />
        {children}
        <Footer/>
        <Toaster/>
      
     
      
        </StoreProvider>
        
      </body>
    </html>
  );
}
